// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package execute

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bed struct {
	ID       uuid.UUID
	IDRoom   uuid.NullUUID
	Name     sql.NullString
	Status   sql.NullString
	CreateAt sql.NullTime
	UpdateAt sql.NullTime
}

type Room struct {
	ID            uuid.UUID
	Name          string
	BedNumber     int64
	PatientNumber int64
	CreateAt      time.Time
	UpdateAt      time.Time
}

type UseBed struct {
	ID       uuid.UUID
	IDBed    uuid.NullUUID
	IDRecord uuid.NullUUID
	Status   sql.NullString
	CreateAt sql.NullTime
	EndAt    sql.NullTime
}

type UseRoom struct {
	ID       uuid.UUID
	IDDoctor string
	IDRoom   string
}
