// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0--rc1
// source: pb/bed.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BedClient is the client API for Bed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BedClient interface {
	GetBed(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error)
}

type bedClient struct {
	cc grpc.ClientConnInterface
}

func NewBedClient(cc grpc.ClientConnInterface) BedClient {
	return &bedClient{cc}
}

func (c *bedClient) GetBed(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error) {
	out := new(GetRes)
	err := c.cc.Invoke(ctx, "/bed.Bed/GetBed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BedServer is the server API for Bed service.
// All implementations must embed UnimplementedBedServer
// for forward compatibility
type BedServer interface {
	GetBed(context.Context, *GetReq) (*GetRes, error)
	mustEmbedUnimplementedBedServer()
}

// UnimplementedBedServer must be embedded to have forward compatible implementations.
type UnimplementedBedServer struct {
}

func (UnimplementedBedServer) GetBed(context.Context, *GetReq) (*GetRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBed not implemented")
}
func (UnimplementedBedServer) mustEmbedUnimplementedBedServer() {}

// UnsafeBedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BedServer will
// result in compilation errors.
type UnsafeBedServer interface {
	mustEmbedUnimplementedBedServer()
}

func RegisterBedServer(s grpc.ServiceRegistrar, srv BedServer) {
	s.RegisterService(&Bed_ServiceDesc, srv)
}

func _Bed_GetBed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedServer).GetBed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bed.Bed/GetBed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedServer).GetBed(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Bed_ServiceDesc is the grpc.ServiceDesc for Bed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bed.Bed",
	HandlerType: (*BedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBed",
			Handler:    _Bed_GetBed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/bed.proto",
}
